os: linux
language: python
python: "3.7"
dist: xenial
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
before_install:
  - export CC
  - export CXX
  - eval "${MATRIX_EVAL}"
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.sh
  - chmod +x cmake-3.13.0-Linux-x86_64.sh
  - ./cmake-3.13.0-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
install:
  - pip install conan
  - conan user
  - conan profile new default --detect --force
  - conan profile update settings.compiler.libcxx=libstdc++11 default
script:
  - cmake . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . -j $(nproc)
  - ctest -V .
